repos:
  # Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  # Frontend hooks (Windows cmd.exe; no WSL needed)
  - repo: local
    hooks:
      - id: eslint-frontend-src
        name: eslint (frontend src)
        entry: cmd /C "cd frontend && npx eslint . --cache --cache-location .eslintcache --fix"
        language: system
        pass_filenames: false

      - id: eslint-frontend-config
        name: eslint (frontend config)
        entry: cmd /C "cd frontend && npx eslint . --cache --cache-location .eslintcache --fix"
        language: system
        pass_filenames: false

      - id: prettier-frontend
        name: prettier (frontend)
        entry: cmd /C "cd frontend && npx prettier --write --ignore-unknown ."
        language: system
        pass_filenames: false
