app = "personal-agent-ste"
primary_region = "iad"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    path = "/health"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
