name: RMS Index

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "Path prefix to index (e.g. backend/ or frontend/src/)"
        required: false
        default: ""
      reset:
        description: "Clear existing index first?"
        required: false
        type: boolean
        default: true
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'tools/**'
      - '.github/workflows/rms-index.yml'

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install \
            openai \
            "supabase==2.4.0" \
            "postgrest==0.10.8" \
            "httpx==0.24.1" \
            tiktoken
      - name: Show versions (debug)
        run: |
          python - <<'PY'
          import importlib.metadata as m
          for pkg in ["supabase","postgrest","httpx"]:
              try: print(pkg, m.version(pkg))
              except: print(pkg, "not installed")
          PY



      - name: Run indexer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
          RMS_REPO: personal-agent-ste
          RMS_BRANCH: main
          RMS_PREFIX: ${{ github.event.inputs.prefix || '' }}
          RMS_RESET: ${{ github.event.inputs.reset && '1' || '' }}
          RMS_SKIP: "backend/static/assets/**,frontend/dist/**,**/node_modules/**"
          RMS_ROOT: ${{ github.workspace }}
        run: |
          python backend/tools/index_repo_ci.py
