name: Supabase Schema Snapshot

on:
  schedule:
    - cron: "0 0 * * *"    # daily at 00:00 UTC
  workflow_dispatch: {}     # allow manual "Run workflow"

permissions:
  contents: write           # needed to commit back to the repo

concurrency:
  group: supabase-schema-snapshot
  cancel-in-progress: false

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install psql + jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client jq

      # Run your script (writes into schema/ by itself)
      - name: Dump Supabase schema to /schema
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DB_POOLER_URL }}  # <-- pooled URL
          SCHEMAS_TO_INCLUDE: public
          OUT_ROOT: schema
          ALLOW_PARTIAL: "1"                                   # keep CI green if a few tables fail
          DEBUG: "0"
        run: |
          chmod +x scripts/dump_schema.sh
          ./scripts/dump_schema.sh
          test -d schema && ls -la schema || (echo "schema/ missing" && exit 1)



      - name: Commit & push if changed
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          if ! git diff --quiet -- schema/; then
            git add schema/
            git commit -m "chore(schema): daily Supabase schema snapshot"
            git push
          else
            echo "No schema changes."
          fi
